name: Deploy Strapi to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node and Build
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - run: npm ci
      - run: npm run build

      - name: Deploy project files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            ./
            !node_modules/**
            !.git/**
            !public/uploads/**
            !database/**
            !.tmp/**
          target: "/var/www/www-root/data/www/strapi"
          overwrite: true
          rm: true

      - name: SSH into VPS and restart pm2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/www-root/data/www/strapi
            pm2 restart all
